apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        auth_basic "Restricted";
        auth_basic_user_file /etc/auth/.htpasswd;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        location /healthz {
          access_log off;
          return 200;
        }
      }
    }